# Generated by Django 5.0.2 on 2024-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('FOOD', 'Food'), ('GAMES', 'Games'), ('ADVENTURE', 'Adventure')], default='Entertainment', max_length=15),
        ),
    ]
