# Generated by Django 5.0.2 on 2024-02-29 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('FOOD', 'Food'), ('GAMES', 'Games'), ('ADVENTURE', 'Adventure'), ('TRAVEL', 'Travel')], default='Entertainment', max_length=15),
        ),
    ]
